server:
  port: ${SERVER_PORT:8080}

stats-server:
  url: ${CLIENT_URL}

logging:
  level:
    ru.practicum.main: DEBUG
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;
    username: ewm
    password: ewm
