version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - DATASOURCE_USERNAME=stat
      - DATASOURCE_PASSWORD=stat
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - DATASOURCE_USERNAME=ewm
      - DATASOURCE_PASSWORD=ewm
      - CLIENT_URL=http://stats-server:9090
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm